#!/bin/bash

DISPLAYS=( `xrandr -q | grep ' connected' | cut -f1 -d' ' | sort` )

if ! (( ${#DISPLAYS[@]} ))
then
	echo "No displays detected" >&2
	exit 1
fi

function assign {
	xrandr --output "$1" --brightness "$2" &
}

if [ "$#" == 0 ]
then
	for DISP in ${DISPLAYS[@]}
	do
		assign $DISP 1.0
	done
	exit 0
elif [ "$#" == 1 ] && [ "${1##*=*}" ]
then
	for DISP in ${DISPLAYS[@]}
	do
		assign $DISP $1
	done
	exit 0
fi

declare -A VALS

while (( "$#" ))
do
	ARG=$1
	DISP=${ARG%=*}
	VAL=${ARG#*=}
	if [ "$VAL" == "$ARG" ] || [ -z "$DISP" ] || [ "$DISP" == 0 ]
	then
		{
			echo -e "Invalid syntax near '$ARG'"
			echo "Examples:"
			echo -e "\t* brightness\n\t\treset all to 1.0\n"
			echo -e "\t* brightness 0.6\n\t\tset all to 0.6\n"
			echo -e "\t* brightness 1=0.7 2= 3=0.4\n\t\tset first to 0.7, second to 1.0, third to 0.4\n"
		} >&2
		exit 1
	fi

	if [ -z "$VAL" ]
	then
		VAL=1.0
	fi

	((DISP--))

	VALS[$DISP]=$VAL

	shift
done

for DISP in "${!VALS[@]}"
do
	VAL=${VALS[$DISP]}
	assign ${DISPLAYS[$DISP]} $VAL
done
